global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  # external_labels:
  #  monitor: 'codelab-monitor'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  # Example job for node_exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # Example job for cadvisor
  - job_name: 'statsd_exporter'
    static_configs:
      - targets: ['statsd_exporter:9102']

  ## gather the metrics of json_exporter application itself
  - job_name: json_exporter
    static_configs:
      - targets: ['json_exporter:7979']
  ## gather the metrics from third party json sources, via the json exporter
  - job_name: json
    metrics_path: /probe
    params:
      - module: [default]
    static_configs:
      targets:
        - https://stranger.social/api/v2/instance
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        ## Location of the json exporter's real <hostname>:<port>
        replacement: host.docker.internal:7979 # equivalent to "localhost:7979"